# Generated by Django 2.1.5 on 2019-01-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=9, verbose_name='Patient ID')),
                ('patient_age', models.IntegerField(default=0, verbose_name='Age')),
                ('patient_name', models.CharField(max_length=50, verbose_name='Name')),
                ('patient_weight', models.CharField(max_length=20, verbose_name='Weight')),
                ('patient_bp', models.CharField(max_length=20, verbose_name='Blood Pressure')),
                ('patient_address', models.CharField(max_length=90, verbose_name='Address')),
                ('registered_date', models.DateTimeField(verbose_name='date registered')),
            ],
        ),
    ]
