# Generated by Django 2.1.5 on 2019-01-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamedic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitations',
            fields=[
                ('medicalrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datamedic.MedicalRecord')),
                ('date', models.DateTimeField(verbose_name='Date of appointment')),
                ('observations', models.TextField(verbose_name='Observable manifestations')),
                ('findings', models.TextField(verbose_name='Clinical findings')),
                ('plan', models.TextField(verbose_name='Plan')),
                ('drugs_prescribed', models.TextField(verbose_name='Drugs prescribed')),
            ],
            bases=('datamedic.medicalrecord',),
        ),
    ]
