# Generated by Django 2.1.5 on 2019-01-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamedic', '0004_visitations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitations',
        ),
    ]
